name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage pyinstaller

    - name: Run Tests
      run: |
        make test
        make integration-test
        make coverage

    - name: Package as Executable
      run: |
        pyinstaller --onefile main.py --name calculator-main

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-main
        path: dist/calculator-main
